### ISSUE TITLE
crash printing eggex

### ISSUE THREAD

**Issue by bar-g** [oils-for-unix/oils#2380]
```
ysh-0.34$ echo $[/[\\0]/]

ysh: _gen/bin/oils_for_unix.mycpp.cc:58306: syntax_asdl::class_literal_term_t* 
expr_to_ast::Transformer::_NonRangeChars(pnode::PNode*): Assertion `0' failed.
```

**Comment by andychu** [comment]
This looks fixed now, thanks for the report

```
ysh-0.35$ echo $[/\\0/]
  echo $[/\\0/]
            ^
[ interactive ]:3: Syntax error in expression (near Id.Expr_DecInt)

```

**Comment by bar-g** [comment]
That is something else, though, and does fail cleanly here, too:
```
ysh-0.35$ echo $[/\\0/]
 echo $[/\\0/]
           ^
[ interactive ]:1: Syntax error in expression (near Id.Expr_DecInt)
```

But the actual issue reported is still the same:
```
ysh-0.35$ echo $[/[\\0]/]
ysh: _gen/bin/oils_for_unix.mycpp.cc:58629: syntax_asdl::class_literal_term_t* expr_to_ast::Transformer::_NonRangeChars(pnode::PNode*): Assertion `0' failed.
```

**Comment by daveads** [comment]
Checking this out
