### ISSUE TITLE
dtc package - printf %b doesn't parse octal forms correctly

### ISSUE THREAD

**Issue by PossiblyAShrub** [oils-for-unix/oils#2401]
```
osh$ printf '%b\n' "\012\013\014\015\336\352\255\276\357" | xxd
00000000: 0a0b 0c0d 5c33 3336 5c33 3532 5c32 3535  ....\336\352\255
00000010: 5c32 3736 5c33 3537 0a                   \276\357.

bash$ printf '%b\n' "\012\013\014\015\336\352\255\276\357" | xxd
00000000: 0a0b 0c0d deea adbe ef0a                 ..........
```

The issue here is that `printf '%b'` shouldn't use `echo -e` formatting but rather `$''` quoting (I think).

This is causing at least one test in the [`dtc` package to fail](https://op.oils.pub/aports-build/2025-08-14-fix.wwz/_tmp/aports-report/2025-08-14-fix/shard2/error/dtc.txt).

**Comment by SeerLite** [comment]
This should be closed, right? Since it seems to have been fixed via #2403.
(Came here from the [blog post explaining this bug](https://aolsen.ca/writings/reproducing-dtc-failure). Very useful and easy to follow!)

**Comment by andychu** [comment]
Yes we can close it now

It still appears on https://github.com/orgs/oils-for-unix/projects/1/views/1 (in the last column)
